# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AttenceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AttenceApp
'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift', '8.9.0-beta'
end

