# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Attendance App-Afnan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Attendance App-Afnan
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore' 
end
