# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Attendance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Attendance
pod 'DTGradientButton'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
end
